version: '3.4'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: database:5432
      PGHOST: database
      PGUSER: postgres
      PGPASSWORD: ""
      PGDATABASE: "postgres"
    volumes:
      - ./reports:/app/reports
    tty: true
    command: sh -c "/wait && npm run-script integtest"

  database:
    image: postgres:12
    volumes:
      - ./migrations/postgres:/docker-entrypoint-initdb.d
