version: '3.4'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./reports:/app/reports
    env_file:
      - ./integration-test.env
    tty: true
    command: sh -c "/wait && npm run-script integtest -- --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/integration-tests.xml"

  database:
    image: postgres:12
    volumes:
      - ./migrations/postgres:/docker-entrypoint-initdb.d
