AWSTemplateFormatVersion: "2010-09-09"
Description: Declares the DynamoDB tables and an execution role graning access to those tables to members of the Spanda API.
Parameters:
  DynamoDBAccessRoleName:
    Description: The role name allowing access to the DynamoDB tables
    Type: String
    Default: SpandaAPIDynamoDBAccess
Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "UsersTable"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "username"
          KeyType: "HASH"
  BankConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "BankConnections"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
  BankAccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "BankAccounts"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
  DynamoAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref DynamoDBAccessRoleName
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt UsersTable.Arn
              -
                Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt BankConnectionsTable.Arn
              -
                Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt BankAccountsTable.Arn
Outputs:
  UsersTableName:
    Description: The name of the users table
    Value: !Ref UsersTable
  UsersTableArn:
    Description: The ARN of the users table
    Value: !GetAtt UsersTable.Arn
  BankConnectionsTableName:
    Description: The name of the bank connections table
    Value: !Ref BankConnectionsTable
  BankConnectionsTableArn:
    Description: The ARN of the bank connections table
    Value: !GetAtt BankConnectionsTable.Arn
  BankAccountsTableName:
    Description: The name of the bank accounts table
    Value: !Ref BankAccountsTable
  BankAccountsTableArn:
    Description: The ARN of the bank accounts table
    Value: !GetAtt BankAccountsTable.Arn
  DynamoAccessRole:
    Description: The ARN of the DynamoDB access role
    Value: !GetAtt DynamoAccessRole.Arn
