AWSTemplateFormatVersion: "2010-09-09"
Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "UsersTable"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "username"
          KeyType: "HASH"
  BankConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "BankConnections"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
  BankAccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "BankAccounts"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
Outputs:
  UsersTableName:
    Description: The name of the users table
    Value: !Ref UsersTable
  BankConnectionsTableName:
    Description: The name of the bank connections table
    Value: !Ref BankConnectionsTable
  BankAccountsTableName:
    Description: The name of the bank accounts table
    Value: !Ref BankAccountsTable
