AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spanda's backend implemented in the Serverless Application Model.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  FinAPIClientId:
    Description: The client id to use to access FinAPI
    Type: String
  FinAPIClientSecret:
    Description: The client secret to use to access FinAPI
    Type: String
  Stage:
    Description: The deployment stage
    Type: String
    Default: "dev"
  DatabaseUser:
    Description: Username of SQL database
    Type: String
    Default: ""
  DatabasePassword:
    Description: Password of SQL database
    Type: String
    Default: ""
  StorageBackend:
    Description: The storage backend to use
    Type: String
    Default: "IN_MEMORY"
  UsersTableName:
    Description: The name of the users table
    Type: String
    Default: ""
  BankConnectionsTableName:
    Description: The name of the bank connections table
    Type: String
    Default: ""

# Globals is a section in your SAM template to define properties common to all your Serverless Function and APIs.
# All the AWS::Serverless::Function and AWS::Serverless::Api resources will inherit the properties defined here.
Globals:
  Api:
    OpenApiVersion: '3.0.1'
  Function:
    Timeout: 45
    Environment:
      Variables:
        REGION: !Sub "${AWS::Region}"
        LOGGER_LEVEL: "debug"
        FINAPI_URL: "https://sandbox.finapi.io"
        FINAPI_CLIENT_ID: !Ref FinAPIClientId
        FINAPI_CLIENT_SECRET: !Ref FinAPIClientSecret
        FINAPI_TIMEOUT: 3000
        PGDATABASE: "postgres"
        PGHOST: !Sub "spanda-database.ctezy0xj9lfh.${AWS::Region}.rds.amazonaws.com"
        PGPORT: "5432"
        PGUSER: !Ref DatabaseUser
        PGPASSWORD: !Ref DatabasePassword
        STORAGE_BACKEND: !Ref StorageBackend
        USERS_TABLE_NAME: !Ref UsersTableName
        BANK_CONNECTIONS_TABLE_NAME: !Ref BankConnectionsTableName

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      DefinitionUri: swagger.yml

  IsUserAuthenticatedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.isUserAuthenticated
      Runtime: nodejs10.x
      Events:
        GetAuthorization:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /users
            Method: get
  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.registerUser
      Runtime: nodejs10.x
      Events:
        PostCredentials:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /users
            Method: post
  AuthenticateAndSaveUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.authenticateAndSaveUser
      Runtime: nodejs10.x
      Events:
        PostLogin:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /oauth/login
            Method: post
  UpdateRefreshTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.updateRefreshToken
      Runtime: nodejs10.x
      Events:
        PostRefreshToken:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /oauth/token
            Method: post
  GetBankByBLZFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.getBankByBLZ
      Runtime: nodejs10.x
      Events:
        GetBankByBLZ:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /banks/{blz}
            Method: get
  GetWebFormIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.getWebFormId
      Runtime: nodejs10.x
      Events:
        PostBankId:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /bankConnections/import
            Method: post
  WebFormCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.webFormCallback
      Runtime: nodejs10.x
      Events:
        PostBankId:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /webForms/callback/{webFormAuth}
            Method: post
  FetchWebFormInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.getWebFormInfo
      Runtime: nodejs10.x
      Events:
        GetWebFormId:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /webForms/{webFormId}
            Method: get
  GetAllowanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.getAllowance
      Runtime: nodejs10.x
      Events:
        GetAllowance:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /allowance
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SpandaAPI:
    Description: "API gateway endpoint URL for the stage"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
  IsUserAuthenticatedFunction:
    Description: "Is User Authenticated Function ARN"
    Value: !GetAtt IsUserAuthenticatedFunction.Arn
  RegisterUserFunction:
    Description: "Register User Function ARN"
    Value: !GetAtt RegisterUserFunction.Arn
  UpdateRefreshTokenFunction:
    Description: "Update Refresh Token Function ARN"
    Value: !GetAtt UpdateRefreshTokenFunction.Arn
  AuthenticateAndSaveUserFunction:
    Description: "Authenticate and Save User Function ARN"
    Value: !GetAtt AuthenticateAndSaveUserFunction.Arn
  GetBankByBLZFunction:
    Description: "Get Bank by BLZ Function ARN"
    Value: !GetAtt GetBankByBLZFunction.Arn
  GetWebFormIdFunction:
    Description: "Get Webform ID Function ARN"
    Value: !GetAtt GetWebFormIdFunction.Arn
  WebFormCallbackFunction:
    Description: "Callback for Webform Function ARN"
    Value: !GetAtt WebFormCallbackFunction.Arn
  FetchWebFormInfoFunction:
    Description: "Fetch WebForm Info Function ARN"
    Value: !GetAtt FetchWebFormInfoFunction.Arn
  GetAllowanceFunction:
    Description: "Get Allowance Function ARN"
    Value: !GetAtt GetAllowanceFunction.Arn
