AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spanda's backend implemented in the Serverless Application Model.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  FinAPIClientId:
    Description: The client id to use to access FinAPI
    Type: String
  FinAPIClientSecret:
    Description: The client secret to use to access FinAPI
    Type: String
  Stage:
    Description: The deployment stage
    Type: String

Globals:
  Function:
    Timeout: 45
    Environment:
      Variables:
        LOGGER_LEVEL: "debug"
        FINAPI_URL: "https://sandbox.finapi.io"
        FINAPI_CLIENT_ID: !Ref FinAPIClientId
        FINAPI_CLIENT_SECRET: !Ref FinAPIClientSecret
        FINAPI_TIMEOUT: 3000

Resources:
  IsUserAuthenticatedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.isUserAuthenticated
      Runtime: nodejs10.x
      Events:
        GetAuthorization:
          Type: Api
          Properties:
            Path: /users
            Method: get
  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.registerUser
      Runtime: nodejs10.x
      Events:
        PostCredentials:
          Type: Api
          Properties:
            Path: /users
            Method: post
  AuthenticateAndSaveUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.authenticateAndSaveUser
      Runtime: nodejs10.x
      Events:
        PostLogin:
          Type: Api
          Properties:
            Path: /oauth/login
            Method: post
  UpdateRefreshTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.updateRefreshToken
      Runtime: nodejs10.x
      Events:
        PostRefreshToken:
          Type: Api
          Properties:
            Path: /oauth/token
            Method: post
  GetBankByBLZFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.getBankByBLZ
      Runtime: nodejs10.x
      Events:
        GetBankByBLZ:
          Type: Api
          Properties:
            Path: /banks/{blz}
            Method: get
  GetWebFormIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.getWebFormId
      Runtime: nodejs10.x
      Events:
        PostBankId:
          Type: Api
          Properties:
            Path: /bankConnections/import
            Method: post
  FetchWebFormInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.getWebFormInfo
      Runtime: nodejs10.x
      Events:
        GetWebFormId:
          Type: Api
          Properties:
            Path: /webForms/{webFormId}
            Method: get
  GetAllowanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spanda/
      Handler: api.getAllowance
      Runtime: nodejs10.x
      Events:
        GetAllowance:
          Type: Api
          Properties:
            Path: /allowance
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SpandaAPI:
    Description: "API gateway endpoint URL for the stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
