version: "3.4"

services:
  app:
    build:
      context: ../../
      dockerfile: ./packages/lambda/Dockerfile
    env_file:
      - ../../integration-test.env
    volumes:
      - ../../reports:/app/packages/lambda/reports
    command: sh -c "/wait && cd packages/lambda && npm run-script integtest -- --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/integtests-lambda.xml"

  database:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../../migrations/postgres/sql:/docker-entrypoint-initdb.d
