version: "3.4"

services:
  app:
    build:
      context: ../../../
      dockerfile: ./DinodimeBackend/packages/lambda/Dockerfile
    env_file:
      - ../../integration-test.env
    volumes:
      - ../../reports:/app/DinodimeBackend/packages/lambda/reports
      - ../../coverages/integration/lambda:/app/DinodimeBackend/packages/lambda/coverages
    command: sh -c "/wait && cd DinodimeBackend/packages/lambda && npm run-script integtest -- --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/integtests-lambda.xml"

  database:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../../migrations/postgres/sql:/docker-entrypoint-initdb.d
