name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and test
      run: |
        cd SpandaServerless/spanda
        npm cit
      env:
        CI: true
